### ISSUE TITLE
Show and Hide Local Pickup with validation

### ISSUE THREAD

**Issue by 000x2a** [WC-Local-Pickup/woocommerce-local-pickup-time#140]
Hello,

I need help with displaying local pick up and hiding it when user changes selection between delivery and local pickup on the checkout page. I also need to incorporate a message if pickup is selected, that local pick up date/time must be entered as a mandatory field.

This is my site:
https://www.provectusdigital.com.au/

Any help much appreciated.

**Comment by timnolte** [comment]
@000x2a I have received your multiple requests for assistance. There are a few existing open issues around this sort of request. Since this has now been by far the most pressing issue I'm going to begin working on this for the next release. You'll find the following open issues related.
* https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/23
* https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/71
* https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/23

**Comment by 000x2a** [comment]
@timnolte Looking forward to the next release. Thanks in advance :)
