### ISSUE TITLE
extension placement

### ISSUE THREAD

**Issue by RemyIwn** [WC-Local-Pickup/woocommerce-local-pickup-time#181]
Hello, 

I explain my problem, I am developing an e-commerce site with the possibility to choose Click&Collect. For this, I installed the Local pickup time select plugin which works very well except that it is not placed where I want 

I would like it to be placed below the delivery mode choices managed by Woocommerce.

Do you know how to do it?

**Comment by timnolte** [comment]
I would recommend turning on the "Limit to Local Pickup Shipping Methods" option and then turning on the Pickup Time for each Local Pickup shipping method in each Zone that you have setup. This enforces the pickup time field to only be present along with the Local Pickup shipping method when it is selected by a user as the chosen shipping method. This actually removes the ability to move the Pickup Time field location but that is required in order to not have problems with requiring the Pickup Time for all shipping methods or having to make it optional if it is required for local pickup.

**Comment by RemyIwn** [comment]
Currently, I have the option to choose the date and time when I choose in-store pickup. Except I want to change the location and place it after the woocommerce delivery methods.
Currently, the date choice is placed below the customer info so not very optimized

![Capture d’écran 2022-07-11 151225](https://user-images.githubusercontent.com/109221111/178755713-aa05d6c1-b18d-4dfc-8d94-769e50120275.png)

I leave you a picture to better understand thank you for your help

**Comment by timnolte** [comment]
Yes, you need to turn on the option I mentioned. It is the last checkbox at the bottom of the plugin settings page and is labeled exactly as I mentioned before. Then there will be another checkbox to enable on the Local Pickup shipping method in each Zone that you have added a Local Pickup Shipping Method.

**Comment by RemyIwn** [comment]
Superb it works perfectly thank you very much for your help
