### ISSUE TITLE
Add Plugin Option to Change If Pickup Time Is Required

### ISSUE THREAD

**Issue by timnolte** [WC-Local-Pickup/woocommerce-local-pickup-time#71]
Right now, the pick-up time is set as a required field.
However, I also ship my products.
For the latter, customers do not need to select a pick-up time.

How can I make sure that the pick-up time is not a required field?

The page I need help with: [http://www.hokkaikitchen.nl](http://www.hokkaikitchen.nl)

Reference: [https://wordpress.org/support/topic/disable-required-field/](https://wordpress.org/support/topic/disable-required-field/)

**Comment by vollmart** [comment]
Hi there,

I would be pleased as well if this issue can be fixed!
Thanks so much for creating this free plug-in for people like me not needing complex yearly paid plugins.

I have less visitors on my webshop, so I can wait for re-installing this plug-in for my website.
However, since the option update will be depending on the 1.4.0 Release, do you have any idea what month it could be released? I am willing to donate an content worthy amount for a simple plugin to make this happen. 

Thanks for you reply in advance.
Regards,
